name: Go report card

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  refresh_go_report_card:
    runs-on: ubuntu-latest
    steps:
    - name: Go report card
      uses: creekorful/goreportcard-action@v1.0
