name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install
        run: make install

      - name: Build
        run: make build

      - name: Test
        run: |
          go test -v -covermode=count -coverprofile=coverage.out ./...

      - name: Coverage
        uses: jandelgado/gcov2lcov-action@v1.1.0
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
